sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - dev
before_deploy:
  - yarn build
  - echo 'preview.sitcon.org' > dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: dev
